config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  draw :api
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :home
  resources :plate_numbers

  root "plate_numbers#index"
end

app/views/shared/_flash_area.html.erb
<%if flash.present? %>
  <nav class="navbar index_9999">
  <div id= "notice">
    <% flash.each do |key, value| %>
        <div class="flash alert-warning <%= key %>">
          <%= value %>
        </div>
    <% end %>
  </div>
</nav>
<script>
  setTimeout(function(){
    $("#notice").remove();
    }, 3000)
</script>
<%end %>


<div id="faye_msg" class="alert_msg faye_msg">
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">车辆信息管理系统</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= nav_bar_active("plate_numbhers", "index") %>" >
          <%=link_to '首页', root_path ,class: 'all_orders' %>
        </li>
        <li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
        <% if current_user.admin? %>
        <%end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%=current_user.name%><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <% if current_user.admin? %>
      <ul class="nav nav-sidebar">
        <li ><h3>牛逼的超管</h3></li>
        <li class="<%= active_by('home') %>"><a href="/">管理首页 <span class="sr-only">(current)</span></a></li>
        <li class="<%= active_by('stores') %>"><a href="/stores">门店管理</a></li>
        <li class="<%= active_by('cars') %>"><a href="/cars">车辆管理</a></li>
        <li class="<%= active_by('auth_applies') %>"><a href="/auth_applies">申请管理</a></li>
        <li class="<%= active_by('tags') %>"><a href="/tags">标签管理</a></li>
      </ul>
  <%end %>
  <% if current_store %>
  <ul class="nav nav-sidebar">
    <li ><h3>门店管理</h3></li>
    <li class="<%= active_by('stores') %>"><a href="/stores/<%= current_store.id %>">我的门店</a></li>
    <li class="<%= active_by('stores/cars') %>"><a href="<%= store_stores_cars_path(current_store.id) %>">门店车列表</a></li>
    <li><%= link_to "Home", main_app.root_path %></li>
    <li><a href="<%= session_path(current_user.id) %>", data-method="delete">退出</a></li>
  </ul>
  <%end %>
</div>