config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  draw :api
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :home
  resources :plate_numbers

  root "plate_numbers#index"
end

app/models/plate_number.rb
class PlateNumber < ActiveRecord::Base
  belongs_to :car
  belongs_to :contact

  validates :number, uniqueness: { message: "车牌号已经存在" }
end

app/controllers/plate_numbers_controller.rb
class PlateNumbersController < ApplicationController
  before_action :set_plant_number, only:[ :edit, :update, :destroy]

  def index
    @plant_numbers = PlateNumber.where(contact: current_cell.contacts).order(id: :desc).page(params[:page]).per(params[:per_page])
    @plant_numbers = @plant_numbers.where("plate_numbers.number like ?", "%#{params[:query]}%") if params[:query].present?

    @result =  current_cell.cell_contacts.joins(:contact).where(contact_id: @plant_numbers.map(&:contact_id)).
      select(:contact_id, 'contacts.name', 'contacts.phone', :cell_address)
  end

  def new
    @plant_numbers = PlateNumber.where(contact: current_cell.contacts).order(id: :desc).page(params[:page]).per(params[:per_page])
    @plant_numbers = @plant_numbers.where("plate_numbers.number like ?", "%#{params[:query]}%") if params[:query].present?

    @result =  current_cell.cell_contacts.joins(:contact).where(contact_id: @plant_numbers.map(&:contact_id)).
      select(:contact_id, 'contacts.name', 'contacts.phone', :cell_address)
  end

  def edit
    @result = current_cell.cell_contacts.joins(:contact).where(contact_id: @plant_number.contact_id).
      select('contacts.name', 'contacts.phone', :cell_address).first
  end

  def create
    PlateNumber.transaction do
      params[:phone] ||= params[:cell_address]
      @contact = Contact.find_by(phone: params[:phone])
      unless @contact.present?
        @contact = Contact.create(name: params[:name], phone: params[:phone])
        @cell_contact = @contact.cell_contacts.create(cell_id: params[:cell_id], cell_address: params[:cell_address])
      end

      @plant_number = PlateNumber.new(number: params[:number], contact: @contact)
      if @plant_number.save
        car_name =  "车#{params[:number]}#{params[:phone]}"
        @car = Car.create(name: car_name)
        @plant_number.update(car: @car)

        render json: { code: 0, msg: "保存成功", url: new_plate_number_path}
      else
        render json: { code: -1, msg: "保存失败, #{@plant_number.errors.full_messages.join(",")}"}
      end
    end
  end

  def update
    PlateNumber.transaction do
      @plant_number = PlateNumber.find(params[:id])
      params[:phone] ||= params[:cell_address]
      @contact = @plant_number.contact
      @cell_contact = @contact.cell_contacts.find_by(cell_id: current_cell.id)
      if @contact.update(name: params[:name], phone: params[:phone]) && @cell_contact
        @cell_contact.update(cell_address: params[:cell_address])
      end

      if @plant_number.update(number: params[:number])
        render json: { code: 0, msg: "保存成功", url: plate_numbers_path}
      else
        render json: { code: -1, msg: "保存失败, #{@plant_number.errors.full_messages.join(",")}"}
      end
    end
  end

  def destroy
    @plant_number.destroy

    redirect_to root_path(page: params[:page])
  end

  private
  def set_plant_number
    @plant_number ||= PlateNumber.find(params[:id])
  end
end

app/helpers/plate_numbers_helper.rb
module PlateNumbersHelper
end

app/views/plate_numbers/edit.html.erb
<div class="container">
  <hr>

  <div class= 'col-md-12'>
    <ul class="list-group">
      <li class="list-group-item">
        <h3>修改车辆信息</h3>
      </li>
      <li class="list-group-item">
        <div class="col-md-12">
          <%= form_for @plant_number, html: {class: ""} do|f| %>
            <%= hidden_field_tag :cell_id, current_cell.id %>
            <div class= 'col-md-3'>
              <%=text_field_tag :number, @plant_number.number, readonly:true, class:"form-control", placeholder: "输入车牌号", required:true %>
            </div>

            <div class= 'col-md-3'>
              <%=text_field_tag :phone, @result.phone, class:"form-control", placeholder: "输入手机" %>
            </div>

            <div class= 'col-md-3'>
              <%=text_field_tag :name, @result.name, class:"form-control", placeholder: "输入姓名" %>
            </div>

            <div class= 'col-md-3'>
              <%=text_field_tag :cell_address, @result.cell_address, class:"form-control", placeholder: "输入地址", required:true %>
            </div>

            <div class= 'col-md-12'>
              <%=f.button '保存', class:"btn-primary btn submit" %>
              <%=link_to '返回首页', root_path, class:"btn-primary btn" %>
            </div>
          <%end  %>
        </div>
        <div>-----</div>
      </li>
    </ul>
  </div>
</div>
<script>
  <%= content_for :js_in_footer do%>
  <%= javascript_tag do %>
  var flag = true;

  $(".submit").on("click", function(e){
    e.preventDefault(); // 移除掉原生的submit处理
    var _form = $(this).parents("form")[0]
    var url =  $(_form).attr("action")
    var type =  $(_form).attr("method")
    var _this = this
    if(!$(_form).valid()){
      return;
    }
    $(_this).attr("disabled", true) //防止重复提交

    $.ajax({
      url: url,
      type: type,
      data: $(_form).serialize(),
      dataType: "json",
      success: function(data){
        handleMessage(data.msg)
        if(data.code == 0){
          location.href = data.url
        }
      },
      error: function(){
        handleMessage("请求失败!")
      },
      complete: function(){
        $(_this).removeAttr("disabled")
      }
    })
  });
  <%end%>
  <%end%>
</script>

app/views/plate_numbers/index.html.erb
<div class="container">
  <hr>

  <div>
    <h4><%= current_cell.name %>车辆信息：</h4>
    <form action="<%= root_path %>">
      <div class="col-md-4 margint-5px">
        <%= text_field_tag :query, params[:query], placeholder: '输入车牌号', class: 'form-control' %>
      </div>

      <div class="col-md-4 margint-5px">
        <%=submit_tag '查找车牌信息', class: 'btn-primary btn' %>
        <%=link_to '新增车牌信息', new_plate_number_path, class: 'btn-default btn' %>
      </div>

    </form>
    <table class="table table-striped table-overflow">
      <thead>
      <tr>
        <th>车辆信息</th>
        <th>操作</th>
      </tr>
      </thead>
      <tbody>
      <% @plant_numbers.each_with_index do |plant_number, i| %>
        <% _contact = @result.detect{|c| c.contact_id == plant_number.contact_id} %>
        <tr>
          <td>
            <div class="panel panel-default">
              <div class="panel-heading"><%= plant_number.number %></div>
              <div class="panel-body">
                <p> [<%= _contact.name %>] <a href="tel:<%= _contact.phone %>"><%= _contact.phone %></a> </p>
                <p> 地址: <%= _contact.cell_address %></p>
              </div>
            </div>
          </td>
          <td width="20%">
            <div class="col-md-6 margint-5px">
              <%= link_to '编辑', edit_plate_number_path(plant_number), class: 'btn-primary btn' %>
            </div>
            <div class="col-md-6 margint-5px">
              <%= link_to '删除', plate_number_path(plant_number, page: params[:page]), method: :delete, data:{confirm: "确认删除[#{plant_number.number}]?"}, class: 'btn-primary btn' %>
            </div>
          </td>
        </tr>
      <%end %>
      </tbody>
    </table>
    <%= paginate @plant_numbers%>
  </div>
</div>
</div>

app/views/plate_numbers/new.html.erb
<div class="container">
  <div class="margint-30"></div>
  <div class='col-md-12'>
    <ul class="list-group">
      <li class="list-group-item">
        <h4>新增车辆信息</h4>
      </li>
      <li class="list-group-item">
        <div class="col-md-12">
          <%= form_for PlateNumber.new, html: {class: ""} do|f| %>
            <%= hidden_field_tag :cell_id, current_cell.id %>
            <div class= 'col-md-3'>
              <%=text_field_tag :number, "浙",class:"form-control", placeholder: "输入车牌号", required:true %>
            </div>

            <div class= 'col-md-3'>
              <%=text_field_tag :phone, nil, class:"form-control", placeholder: "输入手机" %>
            </div>

            <div class= 'col-md-3'>
              <%=text_field_tag :name, nil, class:"form-control", placeholder: "输入姓名" %>
            </div>

            <div class= 'col-md-3'>
              <%=text_field_tag :cell_address, "226.", class:"form-control", placeholder: "输入地址", required:true %>
            </div>

            <div class= 'col-md-12'>
              <%=f.button '保存', class:"btn-primary btn submit" %>
              <%=link_to '返回首页', root_path, class:"btn-primary btn" %>
            </div>
          <%end  %>
        </div>
        <div>-----</div>
      </li>
    </ul>

    <div>
      <table class="table table-striped table-overflow">
        <thead>
        <tr>
          <th>车辆信息</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <% @plant_numbers.each_with_index do |plant_number, i| %>
          <% _contact = @result.detect{|c| c.contact_id == plant_number.contact_id} %>
          <tr>
            <td>
              <div class="panel panel-default">
                <div class="panel-heading"><%= plant_number.number %></div>
                <div class="panel-body">
                  <p> [<%= _contact.name %>] <a href="tel:<%= _contact.phone %>"><%= _contact.phone %></a> </p>
                  <p> 地址: <%= _contact.cell_address %></p>
                </div>
              </div>
            </td>
            <td width="20%">
              <div class="col-md-6 margint-5px">
                <%= link_to '编辑', edit_plate_number_path(plant_number), class: 'btn-primary btn' %>
              </div>
              <div class="col-md-6 margint-5px">
                <%= link_to '删除', plate_number_path(plant_number, page: params[:page]), method: :delete, data:{confirm: "确认删除[#{plant_number.number}]?"}, class: 'btn-primary btn' %>
              </div>
            </td>
          </tr>
        <%end %>
        </tbody>
      </table>
      <%= paginate @plant_numbers%>
    </div>
  </div>
</div>

<script>
  <%= content_for :js_in_footer do%>
  <%= javascript_tag do %>
  var flag = true;
  $("#phone").on("change", function(){
    if(flag) {
      flag = false;

      $.ajax({
        url: "/api/contacts",
        type: "get",
        data: {phone: $(this).val()},
        dataType: "json",
        success: function (data) {
          if (data.code == 0) {
            var _data = data.data
            $("#name").val(_data.name);
            $("#cell_address").val(_data.cell_address);
            $("#name").attr("readonly", true)
            $("#cell_address").attr("readonly", true)
          }else{
            $("#name").val("");
            $("#cell_address").val("226.");
            $("#name").removeAttr("readonly")
            $("#cell_address").removeAttr("readonly")
          }
        },
        error: function () {
          handleMessage("请求失败!")
        },
        complete: function () {
          flag = true
        }
      })
    }
  })

  $(".submit").on("click", function(e){
    e.preventDefault(); // 移除掉原生的submit处理
    var _form = $(this).parents("form")[0]
    var url =  $(_form).attr("action")
    var type =  $(_form).attr("method")
    var _this = this
    if(!$(_form).valid()){
      return;
    }
    $(_this).attr("disabled", true) //防止重复提交

    $.ajax({
      url: url,
      type: type,
      data: $(_form).serialize(),
      dataType: "json",
      success: function(data){
        handleMessage(data.msg)
        if(data.code == 0){
          location.href = data.url
        }
      },
      error: function(){
        handleMessage("请求失败!")
      },
      complete: function(){
        $(_this).removeAttr("disabled")
      }
    })
  });
  <%end%>
  <%end%>
</script>